import Head from "next/head";
import Navigation from "./navigation";
import { useState, useEffect, useRef, useContext } from "react";
import { useMetamask } from "@thirdweb-dev/react";

import Alert from "./alert";
import Web3WalletContext, { WalletNames } from "../context/Web3WalletContext";

interface Props {
  children?: React.ReactNode
}

const Layout = ({ children }: Props) => {
  // STATE
  const [walletName, setwalletName] = useState<WalletNames>("meta_mask")
  const [alert, setAlert] = useState({ type: "success", message: "test" });
  const { connectedWallet } = useContext(Web3WalletContext)


  return (
    <>
      <Head>
        <title>NextWind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className="mx-auto">
        {/* use <section> tags in page level to seperate content */}
        {children}
        {/* EXAMPLE CONTENT STRUCTURE - section > div.container  */}
        <section>
          <div className="container mx-auto">
            {connectedWallet.address && <p>address: {connectedWallet.address}</p>}
            {connectedWallet.chainId && <p>chainId: {connectedWallet.chainId}</p>}
            {connectedWallet.network && <p>network: {connectedWallet.network}</p>}
            {/* {message && <p>STATUS MESSAGE: {message}</p>} */}
          </div>
        </section>
        {alert && <Alert type={alert.type} message={alert.message} />}
      </main>
    </>
  );
};

export default Layout;
