import Head from "next/head";
import Navigation from "./navigation";
import { useState } from "react";
import Alert from "./alert";
import { useWeb3WalletInfo } from "../services/web3_wallet/Web3WalletInfo";

interface Props {
  children?: React.ReactNode
}
const Layout = ({ children }: Props) => {
  // STATE
  const [alert, setAlert] = useState({ type: "success", message: "test" });
  const { address, chainId, network } = useWeb3WalletInfo();


  return (
    <>
      <Head>
        <title>NextWind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation handleAlert={setAlert} />
      <main className="mx-auto">
        {/* use <section> tags in page level to seperate content */}
        {children}
        {/* EXAMPLE CONTENT STRUCTURE - section > div.container  */}
        <section>
          <div className="container mx-auto">
            {address && <p>address: {address}</p>}
            {chainId && <p>chainId: {chainId}</p>}
            {network && <p>network: {network}</p>}
            {/* {message && <p>STATUS MESSAGE: {message}</p>} */}
          </div>
        </section>
        {alert && <Alert type={alert.type} message={alert.message} />}
      </main>
    </>
  );
};

export default Layout;
